/*ADICIONANDO NOVA COLUNA, PARA CRIAÇÃO DE UM ID, PARA PRIMARY KEY*/
ALTER TABLE NOTA_FISCAL
ADD ID_NOTA NUMBER;

CREATE SEQUENCE SEQ_NOTA START WITH 1 INCREMENT BY 1;

UPDATE NOTA_FISCAL
SET ID_NOTA = SEQ_NOTA.NEXTVAL;

/*CRIANDO A CHAVE PRIMÁRIA*/
ALTER TABLE NOTA_FISCAL
ADD CONSTRAINT PK_NOTA PRIMARY KEY (ID_NOTA);