ALTER TABLE NOTA_FISCAL
ADD CONSTRAINT PK_NF
PRIMARY KEY (NÚMERO);

SELECT MAX(DT_EMISSAO)
FROM NOTA_FISCAL;

SELECT NÚMERO
FROM NOTA_FISCAL
WHERE NÚMERO IS NULL;

SELECT NÚMERO
FROM NOTA_FISCAL
WHERE NÚMERO IN
    (SELECT NÚMERO 
    FROM NOTA_FISCAL
    GROUP BY NÚMERO
    HAVING COUNT(*) > 1);