CREATE TABLE nota_fiscal ( chave_acesso VARCHAR2(50),
  modelo VARCHAR2(150),
  serie NUMBER(10),
  NÚMERO NUMBER(10),
  natureza_oper VARCHAR2(150),
  dt_emissao DATE,
  evento_recente VARCHAR2(26),
  dt_hr_evento_recente DATE,
  cpf_cnpj_emitente VARCHAR2(20),
  razao_social_emitente VARCHAR2(128),
  ie_emitente NUMBER(15),
  uf_emitente VARCHAR2(2),
  munic_emitente VARCHAR2(50),
  cod_orgao_sup_dest NUMBER(6),
  orgao_sup_dest VARCHAR2(80),
  cod_orgao_dest NUMBER(6),
  orgao_dest VARCHAR2(150),
  cnpj_dest VARCHAR2(15),
  nome_dest VARCHAR2(150),
  uf_dest VARCHAR2(2),
  indicador_ie_dest VARCHAR2(30),
  destino_oper VARCHAR2(100),
  consumidor_final VARCHAR2(30),
  presenca_comprador VARCHAR2(100),
  valor_nf NUMBER(10, 2));
  
  --AUMENTO NECESSÁRIO NO TAMANHO DESSA COLUNA
  ALTER TABLE NOTA_FISCAL MODIFY MUNIC_EMITENTE VARCHAR2(70);
  ALTER TABLE NOTA_FISCAL MODIFY VALOR_NF NUMBER(12,2);
  
  CREATE TABLE nota_fiscal_item ( chave_acesso VARCHAR2(50),
  modelo VARCHAR2(150),
  serie NUMBER(10),
  NÚMERO NUMBER(10),
  natureza_oper VARCHAR2(150),
  dt_emissao DATE,
  cpf_cnpj_emitente VARCHAR2(20),
  razao_social_emitente VARCHAR2(128),
  ie_emitente NUMBER(15),
  uf_emitente VARCHAR2(2),
  munic_emitente VARCHAR2(50),
  cod_orgao_sup_dest NUMBER(6),
  orgao_sup_dest VARCHAR2(80),
  cod_orgao_dest NUMBER(6),
  orgao_dest VARCHAR2(150),
  cnpj_dest VARCHAR2(15),
  nome_dest VARCHAR2(150),
  uf_dest VARCHAR2(2),
  indicador_ie_dest VARCHAR2(30),
  destino_oper VARCHAR2(100),
  consumidor_final VARCHAR2(30),
  presenca_comprador VARCHAR2(100),
  num_prod NUMBER(4),
  desc_prod VARCHAR2(150),
  cod_ncm_sh NUMBER(10),
  ncm_sh VARCHAR2(100),
  cfop NUMBER(4),
  qtde NUMBER(10,2),
  unid VARCHAR2(20),
  vlr_unit NUMBER(12,2),
  vlr_total NUMBER(14,2));
  
  ALTER TABLE NOTA_FISCAL_ITEM MODIFY NCM_SH VARCHAR2(270);
  ALTER TABLE NOTA_FISCAL_ITEM MODIFY MUNIC_EMITENTE VARCHAR2(80);